version: 0.0
os: linux
files:
   - source: /
     destination: /dev/Portfolio
hooks:
   BeforeInstall:
    - location: scripts/stopnode.sh
      runas: root
   AfterInstall:
    - location: scripts/startnode.sh
      runas: root
