version: 0.0
os: linux
files:
   - source: /
     destination: /var/tmp/node
hooks:
   BeforeInstall:
    - location: /var/tmp/scripts/stopnode.sh
      runas: root
   AfterInstall:
    - location: /var/tmp/scripts/startnode.sh
      runas: root
